---
# tasks file for LEI
- name: Install eclipse
  shell: snap install eclipse --classic
  

- name: Check if MARS is installed
  stat:
    path: /opt/mars/Mars4_5.jar
  register: stat_mars

- name: Make MARS dir
  file: path="/opt/mars" state=directory

- name: Download MARS
  get_url: 
    url="http://courses.missouristate.edu/KenVollmar/mars/MARS_4_5_Aug2014/Mars4_5.jar"
    dest="/opt/mars/"
  when: stat_mars.stat.exists == False
  
