---
# tasks file for LABI---
# tasks file for P1

- name: Install geany
  package:
    name: geany
    state: present

- name: Install wireshark
  package:
    name: wireshark
    state: present

- name: Install python3-pip
  package:
    name: python3-pip
    state: present