---
# tasks file for common
- name: Install locales
  package:
    name: locales
    state: present

- name: Select default locale and keymap
  shell:
    locale-gen pt_PT;
    locale-gen pt_PT.UTF-8;
    update-locale LANG=pt_PT.UTF-8;
    localectl set-keymap --no-convert pt;
    if ! grep -q "setxkbmap pt" ~/.bashrc; then
      echo 'setxkbmap pt' >> /home/vagrant/.bashrc;
    fi
  args:
    executable: /bin/bash


- name: Create user 'glua'
  user: 
    name: glua
    password: $6$/00FKYccjoihoqKB$59oFRn8ehB5HdjhNGjTSNgFoOlhLdxZrQRErORe7SQFVzpvoi5hgUNugchqm9d76FBONfU6fu5YtcJ0rUx4Sj.
    shell: /bin/bash
    groups: admin,sudo
    append: yes
    state: present
    system: no

- name: Remove user 'ubuntu'
  user: 
    name: ubuntu
    remove: yes
    state: absent

- name: Fix glua_HOME permissions
  file:
    dest: /home/glua/
    recurse: yes
    owner: glua
    group: glua
    state: directory

- name: Install xubuntu-core
  package:
    name: xubuntu-core
    state: present

- name: Hide vagrant user
  copy:
    dest: /var/lib/AccountsService/users/vagrant
    content: 
      SystemAccount=true

- name: Install chromium
  package:
    name: chromium-browser
    state: present

- name: Install evince
  package:
    name: evince
    state: present

- name: Install libreoffice
  package:
    name: libreoffice
    state: present

- name: Install supertux
  package:
    name: supertux
    state: present

- name: Install vlc
  package:
    name: vlc
    state: present

- name: Install openjdk-8-jdk
  package:
    name: openjdk-8-jdk
    state: present

- name: Check if vscode is installed
  command: dpkg-query -W vscode
  register: vscode_check_deb
  failed_when: vscode_check_deb.rc > 1
  changed_when: vscode_check_deb.rc == 1

- name: Download vscode
  get_url: 
    url="https://go.microsoft.com/fwlink/?LinkID=760868"
    dest="/tmp/vscode.deb"
  when: vscode_check_deb.rc == 1

- name: Install vscode
  apt: deb="/tmp/vscode.deb"
  when: vscode_check_deb.rc == 1
